language: java
jdk:
- oraclejdk8

install: 
 - wget --no-check-certificate https://files.zyuiop.net/spigot-1.10.jar -O spigot.jar
 - mvn -q org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=spigot.jar -DgroupId=org.spigotmc -DartifactId=spigot -Dversion=1.10.2-R0.1-SNAPSHOT -Dpackaging=jar

deploy:
  provider: script
  skip_cleanup: true
  script: /bin/bash script/deploy.sh
  on:
    repo: zyuiop/RPMachine
    branch: master
