language: java
jdk:
- oraclejdk8

install: 
 - wget --no-check-certificate https://files.zyuiop.net/spigot-1.10.2.jar -O spigot.jar
 - mvn -q org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=spigot.jar -DgroupId=org.spigotmc -DartifactId=spigot -Dversion=1.10.2-R0.1-SNAPSHOT -Dpackaging=jar
 - wget --no-check-certificate https://files.zyuiop.net/spigot-1.8.3.jar -O spigotb.jar
 - mvn -q org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=spigotb.jar -DgroupId=org.bukkit -DartifactId=craftbukkit -Dversion=1.8.3-R0.1-SNAPSHOT -Dpackaging=jar
 - wget --no-check-certificate https://archive.zyuiop.net/BukkitBridge/bukkitbridge-latest.jar -O bukkitbridge.jar
 - mvn -q org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=bukkitbridge.jar -DgroupId=net.zyuiop -DartifactId=bukkitbridge -Dversion=1.0.0-SNAPSHOT -Dpackaging=jar

deploy:
  provider: script
  skip_cleanup: true
  script: /bin/bash script/deploy.sh
  on:
    repo: zyuiop/RPMachine
    branch: master
