language: java
jdk:
- oraclejdk8
install: ./script/prebuild.sh
deploy:
  provider: script
  skip_cleanup: true
  script: /bin/bash script/deploy.sh
  on:
    repo: zyuiop/RPMachine
    branch: master
