createcity:
  price: 500 # Prix de création de ville
  incrfactor: 100 # Le prix réel de création de ville vaut 'price + incrfactor * nombre de villes existantes'

# paliers de villes
floors:
   - inhabitants: 0 # Nombre d'habitants nécessaire pour obtenir ce pallier
     name: Bourg # Nom du pallier
     max-chunks: 15 # Nombre maximum de chunks d'une ville à ce pallier
     max-taxes: 1 # Impot maximum par bloc percevable par cette ville
     chunk-price: 150 # Prix d'un chunk pour cette ville

money:
  symbol: $
  baseAmount: 150.0

# database: net.zyuiop.rpmachine.database.bukkitbridge.BukkitBridgeDatabase
database: net.zyuiop.rpmachine.database.filestorage.FileStorageDatabase