name: RPMachine
main: net.zyuiop.rpmachine.RPMachine
version: "1.0 for MC 1.14.4"
api-version: "1.14"
authors: [zyuiop]
softdepend: [BukkitBridge]
commands:
   money:
     description: Obtient votre monnaie actuelle
     usage: /money
   home:
     description: Vous téléporte à votre home
     usage: /home
   spawn:
     description: Vous téléporte au spawn du monde
     usage: /spawn
   sethome:
     description: Définit votre home
     usage: /sethome
   fly:
     description: Active/Désactive le fly
     usage: /fly
   info:
     description: Commande d'aide
     usage: /help
   myshops:
     description: Affiche vos shops
     usage: /myshops
   job:
     description: Choisit un job
     aliases: [jobs]
     usage: /job [list] [info <nom>] [choose <nom>]
   bypass:
     description: Autorise le bypass des zones de villes
     usage: /bypass
     permission: rp.bypass
   runtaxes:
     description: Exécute le paiement des impôts de force.
     usage: /runtaxes
     permission: rp.runtaxes
   actas:
     description: Agit en tant qu'une entité
     usage: /actas
permissions:
   rp.bypass:
     default: op
   rp.runtaxes:
     default: op
   rp.createcity:
     default: true