name: RPMachine
main: net.zyuiop.rpmachine.RPMachine
version: "1.0 for MC 1.14.4"
api-version: "1.14"
authors: [zyuiop]
softdepend: [BukkitBridge]
commands:
   spawn:
     description: Vous téléporte au spawn du monde
     usage: /spawn
   sethome:
     description: Définit votre home
     usage: /sethome
   fly:
     description: Active/Désactive le fly
     usage: /fly
   info:
     description: Commande d'aide
     usage: /help
   bypass:
     description: Autorise le bypass des zones de villes
     usage: /bypass
     permission: rp.bypass
   runtaxes:
     description: Exécute le paiement des impôts de force.
     usage: /runtaxes
     permission: rp.runtaxes
permissions:
   rp.bypass:
     default: op
   rp.runtaxes:
     default: op
   rp.createcity:
     default: true